src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

the target capacity must be lower or equals to the maxAllowed.

Never exceed the maxAllowed

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Reverts jenkinsci/ec2-fleet-plugin#1

Revert "Never exceed the maxAllowed"

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

this will fix [this issue](https://issues.jenkins-ci.org/browse/JENKINS-43799?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27ec2-fleet-plugin%27)

fix fsRoot reset

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Added a check eliminating unnecessary modify requests when it would provision 0 nodes

Eliminate unnecessary modify requests when provisioning

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Refactored `updateStatus()` to remove Jenkins nodes from the spot fleet that are missing, terminated, stopped, stopping, or shutting-down.
This PR addresses #11 and #9 as well as the root cause of #37 and possibly #36.

Remove terminated or missing spot instances

---

README.md

Autoscaling doesn't work unless you have the proper permissions.  Be explicit about them 
(via https://stackoverflow.com/a/52818902/2063546)

Include better instructions for enabling autoscaling

---

WINDOWS.md
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNode.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2OnlineCheckScriptCause.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-onlineCheckScript.html
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Online check script

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

#167 Fix concurrent provision and update

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/RegionInfo.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RegionInfoTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Show region description along with region code without upgrading SDK. We rely on our enum and fallback to SDK enum to gather all the latest regions.

Show region description along with region code

---

src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java

As requested in PR: https://github.com/jenkinsci/ec2-fleet-plugin/pull/195

Add AutoScalingGroup client test

---

CONTRIBUTING.md

Added contributing instructions so it's easier for future contributors.

Add CONTRIBUTING.md to project

---

pom.xml

Adding imuqtadir as maintainer for project

Add maintainer for project

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Fixing log messages and trying to avoid noise.

Fix log messaging and reduce noise

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java

Delete EC2 instance when Jenkins agent is deleted. Related to #99

Delete instance when agent is deleted manually

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java

Display full region name for EC2FleetLabel similar to EC2FleetCloud. I will be refactoring the common logic in separate PR

Add full regionName for EC2FleetLabelCloud

---

src/main/java/com/amazon/jenkins/ec2fleet/utils/AWSUtils.java

Adding retry policy to ClientConfiguration

Add SDK client retry

---

README.md

Document answer from #178 within the readme and provide a few more details

Add comparison to EC2-Plugin to the README

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java

Fix null for AWS Permissions

---

README.md

Fix grammar/spelling mistakes in the readme

Clean up the Readme

---

docs/CONFIGURATION-OPTIONS.md
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNode.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-maxTotalUses.html
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithHistory.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2MaxTotalUsesRetentionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Add maxTotalUses to cap builds for each instance

Add maxTotalUses to cap builds for each instance

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java

AWS Creds can be null in case of instance profile.

Allow AWS Creds to be null for instance profile

---

src/main/java/com/amazon/jenkins/ec2fleet/utils/AwsPermissionChecker.java

Fix test-connection for fleet

---

pom.xml

**Description:** Updating with new owners as the previous devs are no longer with the team

Update developers in pom.xml

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

- Making planned node name unique per EC2FleetCloud. Planned node name is used in logs from the plugin and Jenkins core node provisioner. 
Before:
```
[hudson.slaves.NodeProvisioner lambda$update$6] FleetNode-0 provisioning successfully completed. We have now 2 computer(s)  
[hudson.slaves.NodeProvisioner lambda$update$6] FleetNode-0 provisioning successfully completed. We have now 3 computer(s)  
```
After:
```
[hudson.slaves.NodeProvisioner lambda$update$6] FleetNode-EC2FleetCloud-1 provisioning successfully completed. We have now 2 computer(s)  
[hudson.slaves.NodeProvisioner lambda$update$6] FleetNode-EC2SpotFleetCloud-1 provisioning successfully completed. We have now 3 computer(s)  
```

Make planned node name unique per EC2FleetCloud

---

README.md
docs/CONFIGURATION-AS-CODE.md

- added missing config
- added warning against Spot Fleet usage as it is now considered legacy API
- updated feature list
- other minor changes

Adding missing config, warning for Spot Fleet usage, other minor changes

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/aws/CloudFormationApi.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java

Clients were throwing errors due to region not being set
Fixes #483

Fleet list was not populating

---

pom.xml
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNamesTest.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudConfigurationAsCodeTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudConfigurationAsCodeTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelParametersTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdaterTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EmptyAmazonEC2.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/AWSUtilsIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/RegionInfoTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2EC2FleetTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleetTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations
* Migrate assertions
* Minor cleanup
* Remove public visibility of test classes and methods
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewd.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5
