src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Since nodes can have more than one executor, we should take that into account when scaling up. The old logic would scale up too aggressively when numExecutors > 1.

Fix scaling to respect numExecutors

---

src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly

The current minimum for minimum cluster size is '1'. However, there are situations where you want to set this to '0' (for example: specific instances for jobs which only occasionally run).
Amazon allows this.
We tested this change, and it works as expected.

Change minimum for minimum cluster size from '1' to '0'

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Locks in plugin should be acquired in the same order.
IdleRetentionStrategy was acquiring Queue lock first, then
locked EC2FleetCloud instance. EC2FleetCould (through CloundNanny)
first acquired lock on itself then on Queue (when adding new node).
Modified ClouldNanny to acquire Queue lock before calling EC2FleetClould
method.
Fixes: https://github.com/jenkinsci/ec2-fleet-plugin/issues/13

Fix potential deadlock

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

This PR simply switches the `Math.round` call to calculating the ceiling.
The original author didn't indicate why they thought round worked best (I think I know why), but using round causes problems with 0 instances online, 1 job in the queue, and 3+ executors configured because: `round((float)1 / x)` where `x > 2` will always return 0.  We have very low usage over the weekends, which means we experience jobs timing out because a second job never enters the queue to trigger the scale up.
I believe the intention behind the current implementation is that you don't want to trigger a scale-up if there's only 1 extra job in the queue.  However, I disagree that `round` produces a correct implementation because of the above scenario.

Use the ceiling to calculate weightedExcessWorkload

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java

The IdleRetentionStrategy has been modified to connect to new spot fleet instance nodes when they are first launched, and to no longer use `tryReconnect()` if the node is offline.
Commentary:  When setting the "Max Idle Minutes Before Scaledown," the retention strategy changes from NoOp to the custom IdleRetentionStrategy.  I think it makes sense for that change to layer on the removal of idle nodes that have exceeded the max idle minutes.  Before this PR, the change not only layered on the removal of idle nodes, but also switched to something closer to the Always retention strategy.  This PR sets the IdleRetentionStrategy back to being like the the NoOp strategy with removal of idle nodes.
Always: https://github.com/jenkinsci/jenkins/blob/0ffb87cbbb43f8ba3498467471d1746e3fb5b749/core/src/ …

Connect at node launch.  Do not reconnect when offline.

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-idleMinutes.html

Added a plugin configuration option named `Always Reconnect`.
When selected, Jenkins will try to reconnect any offline EC2 Fleet Node during each IdleRetentionStrategy check.
Additional Changes:
- The `Max Idle Minutes Before Scaledown` option is now required with 0 as an acceptable value.  There is a help tip for that states "0 for no scaledown" 
- Every EC2 Fleet Node will now have an IdleRetentionStrategy, even if idleMinutes is set to 0 (or null for legacy configurations).
This addresses several concerns raised in #41 after the release of version 1.1.8 which included #42

Always reconnect option

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-fleet.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

For #21 
- Don't show non active (active are only ```submitted```, ```active```, ```modification```) fleets by default on configuration page
- Add checkbox to show all fleets
- Always include selected fleet in result even if non active

#21 Don't show non active fleets by default in configuration

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

```EC2FleetCloud``` is using field ```credentialsId``` which conflicts on Jenkins UI with similar field from ```computerConnector``` as result Jenkins pass to server side for ```test connection``` or other operations value from incorrect ```credentialsId```
As we cannot rename var from ```computerConnector``` rename our from ```credentialsId``` to ```awsCredentialsId``` but keep both for back compatibility.

#15 Fix test connections (avoid conflict credentialsId with ssh creds)

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java

Some users get ```RequestLimitExceeded``` issue #60 when they have more than one fleet. Need to reduce the number of calls to EC2 API to avoid exception but keep updating rating as is if possible so avoid dead executors on Jenkins side. 
The actual issue is ```EC2FleetCloud.updateStatus(...)``` method which checks if instances for the fleet were terminated, non-fixed version does one call to EC2 API per instance, each ```10 sec```, as a result, if you reach some number of instances you reach the limit of calls to EC2 API. Doesn't matter if you have a big fleet or a few small.
In fact, EC2 API for describe instances supports batch mode [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) which could significantly reduce the amount of calls.
With fix …

#60 check if instances terminated in batch

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-name.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java

Most clouds plugins have a name property and ability to control it within the UI.
It will be nice to distinguish between cloud instances by name and by that simplify automation in an idempotent manner (replace cloud by name and type).
Kept the original behaviour, so if the cloud name is empty or null, it will be still the default name.

Added ability to control the cloud name

---

src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java
src/test/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategyTest.java

Include into ```IdleRetentionStrategy``` check for ```isIdle()``` which report ```false``` if node executes smt right now, additional to ```getIdleStartMilliseconds()``` which could return ```Long.MIN_VALUE``` in some cases, as result node will be assumed as idle. 
Based on Jenkins [CloudRetentionStrategy](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/CloudRetentionStrategy.java)

#36 don't reclaim node if not idle now

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-endpoint.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EmptyAmazonEC2.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Fix for #103 #51
1. Make region list on Configuration page as mix of static region list from ```org.jenkins-ci.plugins:aws-java-sdk``` and dynamic call to EC2 ```describeRegions``` to be able provide list even if call fails or doesn't provide required region, like China 
1. Upgrade ```org.jenkins-ci.plugins:aws-java-sdk``` dependency to latest version which still support Jenkins ```1.6.x``` to improve list of regions
1. Allow configure custom ```endpoint``` for case when region list doesn't have proper region.

Allow custom endpoint and fix region list

---

README.md
pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2TerminationCause.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-disableTaskResubmit.html
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Cover additional cases for #104 
- Parametrized jobs require schedule ```actions``` which represent actual parameter values together with the original job 
- Pipeline job doesn't fail when the node is disconnected, instead, it's waiting, so we need to abort it from the plugin as no way to reconnect node and reschedule
- Add configuration to disable auto resubmit (by default ```enabled```)
- Integration tests were added for freestyle job and parametrized
- Pipeline test is done manually as pipeline plugin requires Jenkins version ```>2``` while we still support Jenkins ```1.x```

Fix auto resubmit job if ec2 terminated

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java

Addon for #76 to do actual connection instead of just checking if the node is online. We need that as a usual policy for Jenkins is a few short intervals connections when node created and then long, minutes and more. It doesn't work for EC2 instance because during short intervals instance in the init process.

Do connection before wait

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
src/main/java/com/amazon/jenkins/ec2fleet/cloud/FleetNode.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

This is awslabs/ec2-spot-jenkins-plugin#12, rebased and cleaned up a bit for this repo.
This works nicely with a SpotFleet weighted by vCPU count (easy in the
management console).

Scale executors by LaunchSpecification weight

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java

During start-up for new instances plugin does ```describeInstances``` calls to get their IP address, one per instance
- Each ```10 sec``` plugin does a few calls
- fleet describe by calling ```describeSpotRequest```
- ```describeInstances``` to find if any instances are terminated (batch call)
- ```describeInstances``` per new instance
This fix eliminate last ```describeInstances``` call by reusing data from previous one, so each ```10 sec``` plugin does no more then ```2 calls```
This should help to avoid ```LimitExceedException``` for accounts with small limit call to EC2 or for small regions, which could have small limit.

Reduce amount of describeInstances calls for fleet update

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-cloudStatusIntervalSec.html
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

We run a large number of build hosts and spot fleet instances in an AWS account and the
default setting of 10 seconds for the CloudNanny checker ran us into API limits with AWS.
This change allows us to set the check interval from 10 seconds to 60 seconds thus keeping
us under the API limits.
This patch adds a new configuration option in the "advanced" section of the EC2 fleet configuration which
controls the interval at which the CloudNanny checker is run.

Make cloud status check interval configurable.

---

README.md
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-noDelayProvision.html
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithHistory.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Jenkins designed to keep capacity as small as possible. It prefers to wait some time when queue has enough pending jobs or pending time reachs some limit. This creates additonal delays between job scheduling and actual execution. 
Historically new capacity is not easy to add or expensive to use for short time. This is not the case for EC2 Linux based instances with per minute billing.
This change added feature to turn off Jenkins default conservative capacity approach and force Jenkins to request new capacity as soon as new job appears in queue and there are no free capacity to execute.
- New configuration option ```No Delay Provision Strategy``` when enabled forces Jenkins to request new capacity immediately.
- New provision startegy with high order created ```NoDelayProvisionStrategy``` …

Add No Delay Provision Strategy

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

Plugin automatically adds cloud name as EC2 instance tag. Format:
```
ec2-fleet-plugin:cloud-name=<cloudName>
```
As result you AWS Console you can easelly find all EC2 instances launched by Plugin if search by ```ec2-fleet-plugin``` or subset of EC2 instances launched for particular cloud ```ec2-fleet-plugin:cloud-name=MyCloud```
**Note** this is non critical feature, if it will fail plugin will continue work without assigned tags. Make sure user which you specify in plugin configuration has ```ec2:CreateTags``` permissions

Tag ec2 instances

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidget.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdater.java
src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleet.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdaterTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java

1. Handle EC2 Spot Fleet ```modifying``` state correctly. Due to the implementation of each modification of fleet not applied immediately and required some time during which ```targetCapacity``` is old. EC2 Spot Fleet [Lifecycle](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-states)
- #156
1. Avoid negative target capacity if fleet updated outside of plugin (a few other cases)
1. Fix widget information
- #147

Handle eEC2 Spot Fleet modifying state

---

README.md
docs/LABEL-BASED-CONFIGURATION.md
src/main/java/com/amazon/jenkins/ec2fleet/AbstractEC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/CloudFormationApi.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudAware.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudAwareUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelParameters.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelUpdater.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNode.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/JenkinsUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/Registry.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/EC2Fleet.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleet.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/auto-scaling-group.yml
src/main/resources/com/amazon/jenkins/ec2fleet/ec2-spot-fleet.yml
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelParametersTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java

This feature auto manages EC2 Spot Fleet or ASG based Fleets for Jenkins based on 
label attached to Jenkins Jobs.
With this feature user of EC2 Fleet Plugin doesn't need to have pre-created AWS resources 
to start configuration and run Jobs. Plugin required just AWS Credentials 
with permissions to be able create resources.
- Plugin detects all labeled Jobs where Label starts from Name configured in plugin configuration ```Cloud Name```
- Plugin parses Label to get Fleet configuration
- Plugin creates dedicated fleet for each unique Label
- Plugin uses [CloudFormation Stacks](https://aws.amazon.com/cloudformation/) to provision Fleet and all required resources
- When Label is not used by any Job Plugin deletes Stack and release resources

Label based configuration

---

README.md
docs/CONFIGURATION-AS-CODE.md
docs/LABEL-BASED-CONFIGURATION.md
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud/config.jelly

Update README, docs and inline help to point out that an AWS User / AWS
Credentials are optional if an AWS Instance Role is configured via an
instance profile.

Document use of EC2 Instance Role

---

src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java

This configures the AmazonAutoScalingClient to be created without
credentials when none are found. 
Credits: @vroy

Allow for instance profile credentials in AutoScaling client

---

README.md

Avoid having broad blanket permissions for AWS by following AWS IAM guidelines of granting least privilege and granting minimal permissions.

Narrow AWS permissions required by plugin

---

src/main/java/com/amazon/jenkins/ec2fleet/AwsPermissionChecker.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/EC2Fleets.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-fleet.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

By clicking 'Test Connections' button, users can verify if they are missing any AWS policies required by the plugin.

Add checking AWS Permission using Test Connection button

---

src/main/java/com/amazon/jenkins/ec2fleet/AbstractEC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java
src/test/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategyTest.java

Excess capacity isn't immediately pruned when max size is decreased or a fleet greater than max allowed was attached to the plugin. 
When max is decreased in the fleet plugin settings, the plugin will prune the nodes which are idle. If the nodes are currently busy, they will NOT be pruned and the build would continue. However, once the build is complete and nodes are idle - they will be removed.

Prune excess idle capacity if greater than max

---

src/test/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategyIntegrationTest.java

Integration tests were failing intermittently as nodes were terminated by Jenkins due to timeout. Fixing this by breaking sleep into multiple parts

Fix timeout for integration test

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java

`computer.getOfflineCause() instanceof OfflineCause.ChannelTermination` does not always hold after an unexpected instance termination.
As reported in issue #121, the offline cause is sometimes simply `hudson.slaves.OfflineCause$SimpleOfflineCause`; this led to executables running on interrupted instances not always being resubmitted.
Rather than handling specific offline causes (and having to enumerate all possibilities), this commit makes it so that active executables are always resubmitted regardless of the host's offline cause (unless `disableTaskResubmit` is specified). This really does seem like the intended behavior - to ensure executables don't require manual intervention in the event the host they're running on goes offline.

Fix executable resubmission behavior on instance termination

---

src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java

Update Autosubmit Integ tests to reflect that we resubmit the build irrespective of the disconnect cause (eg. ChannelTermination, SimpleOfflineCause: ByCLI/User)

Update Autosubmit Integ tests

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java

Instead of masking termination exceptions, rethrow exception. Currently even if we encounter exception we proceed with cloud nanny assuming the termination as succeeded. This leads to lot of confusion. We would now log the error and also rethrow the exception.

Rethrow failed termination exceptions

---

README.md
src/main/java/com/amazon/jenkins/ec2fleet/CloudFormationApi.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java

`getInstance()` is deprecated, we should use `get()`
Technically `getInstanceOrNull()` is the true new equivalent to `getInstance()`, but we shouldn't have any problem using just `get()` since we never handle null Jenkins.
In their own words from the `getInstanceOrNull` javadoc: 
>  {@link #get} is what you normally want.
<p>In certain rare cases you may have code that is intended to run before Jenkins starts or while Jenkins is being shut down.
For those rare cases use this method.

Replace deprecated getInstance() with get()

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudIntegrationTest.java

Fixes #235 
These aren't used or displayed in the label fleet configuration

Remove unused fields from LabelCloud constuctor

---

README.md
src/main/java/com/amazon/jenkins/ec2fleet/CloudFormationApi.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java

I broke the tests in #237 because we still needed to mock `Jenkins.getInstance()` due to them being used in Jenkins code we don't control 😔
This change reverts that, and should also fix the `descriptorImpl_doTestConnection` tests which have been broken since #225

Fix tests, revert #237

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java

Fixes #172 
In 172 we don't scale up from 0 because plannedNodes persist in Jenkins's plannedCapacitySnapshot. This happens when the fleet configuration changes in between Jenkins calling provision() on a fleet and the fleet's next update cycle where it actually tries to scale up. 
This change uses ScheduledFutures to cancel plannedCapacitySnapshot futures after a timeout of 3 cloud update cycles unless explicitly canceled. This means that if the fleet is modified, or if a fleet is completely removed, we're still covered.

Remove plannedCapcity after a timeout

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

Sometimes we terminate the instances successfully however we immediately call DescribeInstances which does NOT reflect recently terminated instance. Due to this delay, we go ahead and re-add the instance as jenkins node.

Remove just terminated instance from current view

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

Get accurate count of instance before scheduling instances for termination. Some scenarios where this is needed:
1. Fleet takes a while to reflect the accurate count which can cause us to go below min threshold
2. Failed termination - Fleet may have target of 0 however there may be instances strangling around (due to termination policy) which would never get deleted. Although, we would add them as Jenkins nodes but these could never really be removed.
This change would help us have accurate count of active instances based on true state of the world

Get accurate count of active instances

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/LazyUuid.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

When user changes plugin config such as `numOfExecutor`, Jenkins creates a new instance and we reassign the `new Cloud` back to existing nodes/computers. However, during initialization of `new Cloud`, the `stats` object remains null and we reassign the null stats to existing cloud. This causes termination to fail. 
When the user clicks save multiple times, we lose the `id.getValue` which causes `IdleRetentionStrategy` thread and `CloudNanny` thread to have different copies of objects. In this scenario, we might add instances to `instancesToTerminate` list however `CloudNanny` continues to refer to newer object.

Fix bug when stats is null for termination

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

After an instance is requested for termination it will still show up for a while until it's fully removed from the fleet. During that time, this log message shows up ever `update`, even though Jenkins has already removed the node. This change just moves the log statement so that if Jenkins has already removed the node, we don't emit this.

Change location of a log to avoid spam

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

If the plugin is updated but the config isn't changed or saved, the cloud object isn't reinitialized and `maxTotalUses` stays null. This change adds a guard against that so people should safely be able to update the plugin
Solves #254

Add null check for maxTotalUses for plugin update

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java

`com.google.common.base.Objects#firstNonNull` has been removed in recent versions of Guava, so consuming this API is a liability. This PR replaces usages of `com.google.common.base.Objects#firstNonNull` with native Java functionality to allow this plugin to be used seamlessly with any version of Guava in the future.

Remove usages of `com.google.common.base.Objects.firstNonNull`

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdater.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/EC2Fleets.java
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdaterTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleetTest.java

See [JENKINS-66310](https://issues.jenkins.io/browse/JENKINS-66310) and [JENKINS-65988](https://issues.jenkins.io/browse/JENKINS-65988). Jenkins core is using [Guava 11.0.1](https://github.com/google/guava/releases/tag/v11.0.1), which was released on January 9, 2012. Jenkins core would like to upgrade to [Guava 30.1.1](https://github.com/google/guava/releases/tag/v30.1.1), which was released on March 19, 2021. Plugins must be prepared to be compatible with both Guava 11.0.1 and Guava 30.1.1 in advance of this core transition.
In particular, this plugin has been identified as using the `com.google.common.collect.MapMaker` API, which has changed between Guava [11.0.1](https://guava.dev/releases/11.0.1/api/docs/com/google/common/collect/MapMaker.html) and …

[JENKINS-66310] Prepare EC2 Fleet for core Guava upgrade

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java

Scale up up to minSize

---

src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java

From a failed pipeline test: 
😩
Adding a second to the sleep so that `idleTime > retentionTime` and the nodes get marked as idle as intended

increase test sleep time from 60s to 61s

---

src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java

Release of 2.3.4 got screwed up because Jenkins forced a password reset after the Confluence monero [hack](https://www.bleepingcomputer.com/news/security/jenkins-projects-confluence-server-hacked-to-mine-monero/). In my efforts to fix it, I got rid of this commit :|

Increase test sleep time

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java

Adding count of builds left for instances as executor status. If the count of builds is set to be unlimited, then we would not be showing the counts.

Add count of builds left for instances

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Whenever the user modifies any configuration setting, the plugin resets the build counts back to `maxTotalBuild`. After debugging, I found that we refer to old cloud object for `CloudNanny` which triggers the plugin to re-add already existing node within Jenkins. This bug probably existed for the longest time however it never affected anything until we add `maxTotalBuild` feature. 
More details: When we run `update()`, the cloud object (`this`) continues to refer to old cloud object in it's initial run (probably because it was scheduled during/prior the configuration save process) while `EC2FleetNode` is already re-assigned with the latest cloud object. This causes us to re-add the node hence resetting the build counts. The `update()` fixes itself in subsequent run however the re-add …

Fix save configuration to avoid resetting build counts

---

src/main/java/com/amazon/jenkins/ec2fleet/AbstractEC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2MaxTotalUsesRetentionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyTest.java

Currently, we do not terminate instance even current capacity goes below min size even if it exhausts maxTotalBuilds. The instance remains in suspended state without taking any new build/jobs. We would now forcefully terminate the instance regardless of the minSize. A new instance would be launched in the next run to satisfy minSize criteria.

Force terminate instance when it exhausts maxTotalBuilds

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/utils/RegionInfo.java
src/test/java/com/amazon/jenkins/ec2fleet/EmptyAmazonEC2.java

Updates various plugin build metadata to more recent versions.

Update plugin parent POM and BOM

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithHistory.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionPerformanceTest.java
src/test/java/com/amazon/jenkins/ec2fleet/RealTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Add minimum spare instances feature to allow faster builds. `Minimum spare size` are the count of instances that will be idle to pick up any upcoming build immediately. Once the build is picked up, we would then replenish `minimum spare size` by launching newer instances. Max cluster size would be respected if adding minimum spare instance size would breach max cluster size. By default, minimum spare instance size is 0. The minimum spare instances do not get terminated if they remain idle for max allow idle time.

Add minimum spare instances feature

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java

*Issue #, if available:*
*Description of changes:*
Adding workflow job plugin dependency to gather parameters. This should work as a temporary fix for now. Long term we can built something like the rebuild plugin which has a UI to save the existing parameters. Tested the changes manually while having multiple builds on single instance and terminating the instance abruptly. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Fix missing params for resubmitted jobs in pipelines

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

This fixes #342.
getCurrentSpareInstanceCount checks in whole Jenkins computers and does not account that we want to check only in given fleet. 
I added a filter to filter worker nodes only from given fleet that is being checked. If we are not checking the computer from given fleet - we continue, we don't want to count the computer as busy computer in given fleet, **because it is not a part of given fleet**.

Fix getCurrentSpareInstanceCount - check busy nodes in given fleet, not whole Jenkins instance

---

docs/CONFIGURATION-AS-CODE.md

Just fix typo in `jcasc` minimal configuration example. It may save some time for consumers of the plugin.
```java
2022-11-24 20:30:34.371+0000 [id=29]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
java.lang.IllegalArgumentException: No hudson.slaves.ComputerConnector implementation found for ssh
```

Fix typo in jcasc configuration example

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelUpdater.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdater.java
src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/utils/AWSUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/utils/EC2FleetCloudAwareUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/utils/JenkinsUtils.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithHistory.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/utils/EC2FleetCloudAwareUtilsTest.java

Upgrading minimum Jenkins version to fix LinkageError seen in agent logs. 
Jenkins Issue: https://issues.jenkins.io/browse/JENKINS-62006
Fix PR: https://github.com/jenkinsci/jenkins/pull/5367 
Why 2.277.2? : lowest LTS version with the fix - https://github.com/jenkins-infra/release/issues/140 
- Monitored scaling of ASGs by plugin for a few hours.  
- Specific and more elaborate test scenario explained [here](https://github.com/jenkinsci/ec2-fleet-plugin/issues/322#issuecomment-1561876560)

Upgrading the minimum required Jenkins version.

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-minSpareSize.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java

- Add clarity to EC2FleetOnlineChecker logs to replace node name `i-0123456789abcdefg` with node display name `EC2FleetCloud1 i-0123456789abcdefg` which includes the cloud name.
- Add help text to minSpareSize
Ran Jenkins with snapshot version of plugin and verified changes.
Before:
```
[INFO  ][com.amazon.jenkins.ec2fleet.EC2FleetOnlineChecker run] Node 'i-0123456789abcdefg' connected. Resolving planned node 
```
After:
```
[INFO  ][com.amazon.jenkins.ec2fleet.EC2FleetOnlineChecker run] Node 'EC2FleetCloud1 i-0123456789abcdefg' connected. Resolving planned node 
```

Fix logs and help

---

src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java
src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java

The plugin computes current demand and available capacity in order to identify excess workload and provision capacity for it. This code is run when jobs are added to queues.
Problems with current computations:
- Available capacity includes both `connectingExecutors` and `plannedCapacitySnapshot`. This can lead to availableCapacity being much higher than reality, esp. for huge fleets and a  busy Jenkins with numerous builds running / queued.
- Current demand changes as capacity is provisioned but queue length remains same. This can be misleading and makes code and logs less readable, especially when dealing with negative current demand.
```
com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply In NodeProvisioner.StrategyDecision -> apply StrategyState{label=spot-workers, …
```

[Fix] Fix computation of excess workload and available capacity

---

src/main/java/com/amazon/jenkins/ec2fleet/AbstractEC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2AgentTerminationReason.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2ExecutorInterruptionCause.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-maxTotalUses.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudWithMeter.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2MaxTotalUsesRetentionStrategyTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyTest.java

#363 
- add and track `EC2AgentTerminationReason` for cases when plugin triggers termination
- [fix] remove unnecessary decrement which could lead to a positive maxTotalUses eventually decrement to -1. 
'-1' has special meaning, means unlimited uses which is the opposite of the maxTotalUses. 
- [fix] remove misleading log to prevent logs like `Agent xxx is still in use by more than one (1) executors.`
- [fix] remove redundant `computer.setAcceptingTasks(false)`
- rename 
- EC2TerminationCause to EC2ExecutorInterruptionCause for clarity
- rename `force` to `overrideOtherSettings` in scheduleToTerminate for clarity
Tested all changes with a snapshot version of the plugin. 
```
[INFO  ][com.amazon.jenkins.ec2fleet.EC2FleetCloud info] EC2FleetCloud1 [spot-workers] Scheduling instance 'i-xxx' …
```

Fix unnecessary decrement of maxTotalUses and add clarity to logs around terminations triggered by plugin 

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNode.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategy.java
src/main/java/com/amazon/jenkins/ec2fleet/JenkinsUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/Registry.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/AWSUtils.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/AwsPermissionChecker.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/CloudFormationApi.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/EC2Api.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/RegionHelper.java
src/main/java/com/amazon/jenkins/ec2fleet/aws/RegionInfo.java
src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/AWSUtilsIntegrationTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/EC2ApiTest.java
src/test/java/com/amazon/jenkins/ec2fleet/aws/RegionInfoTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java
src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleetTest.java

Refactoring for clarity, readability: 
- Added class comments for Jenkins extensions / subtype implementations
- Consolidating AWS related classes into their own package
- Reduced job sleep time from 30s to 5s to make integration tests run faster

Refactoring for clarity

---

README.md
docs/SETUP-WINDOWS-AGENT.md
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputer.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-name.html
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java

Handling following issue
- https://github.com/jenkinsci/ec2-fleet-plugin/issues/329
- Verified via UI, `slave` terminology is updated
```[tasklist]
- [ X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ X ] Ensure that the pull request title represents the desired changelog entry
- [ X ] Please describe what you did
- [ X ] Link to relevant issues in GitHub or Jira
- [ X ] Link to relevant pull requests, esp. upstream and downstream changes
- [ X ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

handling issue 329

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-name.html
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud/config.jelly
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Handling issue #387 
- This change will make cloud name unmodifiable once a cloud object is created. Once a cloud object is created, the `configureClouds` page will make the name textbox readOnly
- Also, fixing validation on cloud name by changing check method from `doCheckCloudName` -> `doCheckName`
- If no cloud name is provided, then a default cloud name of "FleetCloud" and "FleetCloudLabel" will be used respectively for an EC2FleetCloud and EC2FleetLabelCloud
- The default textbox when a cloud is created will now be blank rather than "FleetCloud"/"FleetCloudLabel". The default name will be handled in the java code, rather than in two separate locations as is now.
- Unit Tests
- Created and saved cloud, reloaded configureClouds and verified textbox is readOnly
- Created and saved …

Handling issue #387 - making cloud name unmodifiable once set initially

---

src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java

Added the method `getMaxTotalUses` which fixes Issue #397 
Verified that set value for `Max Total Uses` persists through config save and apply on Jenkins version 2.277.2 and 2.414. Previous behavior with lack of getter method was to replace with default value of `-1` every time on Cloud Configuration page.

add getMaxTotalUses

---

docs/CONFIGURATION-AS-CODE.md
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud/config.jelly

Issue: #349 
Clarifying the Always Reconnect property of EC2 Fleet cloud configurations based on #349 on Jenkins UI.
Created two cloud configurations with identical attributes outside of Always Reconnect. Verified that Always Reconnect only has unique behavior when Instances on EC2 Fleet reboot. Jenkins restart will always reconnect to EC2 Fleet regardless of whether Always Reconnect is included in configuration. Nodes will stay offline if instance is rebooted and Always Reconnect is not selected.

clarify Always Reconnect property of EC2 Fleet cloud configurations

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNames.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud/config.jelly
src/test/java/com/amazon/jenkins/ec2fleet/CloudNamesTest.java
src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java

Make existing clouds with duplicate names editable for UI users. As part of changes to [fix cloud tracking](https://github.com/jenkinsci/ec2-fleet-plugin/pull/383), cloud name must be unique across all clouds. As users update to the new release, existing clouds may have the same name, so must be editable in order to update to unique names. Once the new unique names are set, then cloud name is final.
I could not find a great way to prevent jenkins from running or have a popup indicating to users upgrading the new jenkins release to check if there cloud names are unique. As part of a troubleshooting or upgrade guide, users can be guided to update any existing clouds with duplicate names.
- Unit tests
- Created existing unique clouds and verified cloud name is editable, then becomes …

making existing duplicate cloud name editable as part of fixes for cloud tracking

---

src/main/java/com/amazon/jenkins/ec2fleet/CloudNames.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloud.java
src/test/java/com/amazon/jenkins/ec2fleet/CloudNamesTest.java
src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudConfigurationAsCodeTest.java
src/test/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/empty-name-configuration-as-code.yml

Suffix generation now uses a randomly generated string instead of incremental for default cloud name generation through UI or empty strings in CasC configurations.
Altered and added Unit Tests in [EC2CloudNamesTest.java](https://github.com/vineeth-bandi/ec2-fleet-plugin/blob/suffix-generation/src/test/java/com/amazon/jenkins/ec2fleet/CloudNamesTest.java) for new functionality.
Added Unit Test in [EC2FleetCloudConfigurationAsCodeTest.java](https://github.com/vineeth-bandi/ec2-fleet-plugin/blob/suffix-generation/src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudConfigurationAsCodeTest.java) for empty strings in CasC.
Tested that both UI and CasC generate default cloud names properly. On creation of new clouds and empty strings in yaml file for UI and CasC, respectively.
Verified …

cleaned up suffix generation for CloudNames and default name for CasC

---

pom.xml
src/main/java/com/amazon/jenkins/ec2fleet/aws/AWSUtils.java

Fixes #492 
When I updated the AWS SDK version in #478 I introduced an issue when configuring a Cloud to use an AWS credential assuming a role.
Verified that it is working as expected running on an instance with this change

Fix for using AWS credential with role
